[package]
name = "http_echo"
version = "0.1.0"
authors = ["Elmar Athmer <elmar.athmer@rewe-digital.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
serde_json = "1.0.44"
